version: '2'
plugins:
  # common
  fixme:
    enabled: true
  git-legal:
    enabled: true
  markdownlint:
    enabled: true
  # ruby/rails
  brakeman:
    enabled: true
  flog:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-54 # https://github.com/codeclimate/codeclimate-rubocop/branches/all?utf8=%E2%9C%93&query=channel%2Frubocop
  # css
  csslint:
    enabled: true
  scss-lint:
    enabled: true

exclude_patterns:
- "db/"
